### ISSUE TITLE
Exposing container lifecycle and pod terminationGracePeriodSeconds configuration in VarnishCluster CRD

### ISSUE THREAD

**Issue by lucasreed** [IBM/varnish-operator#109]
Hello, great project! I have a use-case where I'd like to add `container[].lifecycle.preStop` configurations into the varnish statefulset that's generated by the `VarnishCluster` CRD, but unfortunately there doesn't seem to be a way to do that currently.

My use case is as follows:
- configured VCL to be a self-routing cluster with consistent hashing
- want 0 downtime when pods move during upgrades (or any other maintenance)
- In conjunction with setting a deregistration timeout on the loadbalancer side of things, increasing the `terminationGracePeriodSeconds` config, and including unused "shutdown" vcl configurations in my vcl ConfigMap, the following lifecycle config on the varnish container will allow for graceful pod removal with no errors or dropped traffic:

```
lifecycle:
  preStop:
    exec:
      command:
      - /bin/bash
      - -c
      - varnishadm vcl.load shutdown /etc/varnish/entrypoint_shutdown.vcl
        && varnishadm vcl.use shutdown && sleep 60
```

Worth mentioning that the `entrypoint_shutdown.vcl` is identical to my main `entrypoint.vcl` except the heartbeat probe between varnish cluster pods will return a 404 to mark it sick to all members to allow traffic to drain and not be sent to that pod.
