### ISSUE TITLE
Enable option to activate the control port on 6082

### ISSUE THREAD

**Issue by arthurlogilab** [IBM/varnish-operator#5]
First off thanks for varnish-operator, we're very happy with the way it works and are using it on one of our projects. 

The application it is caching has a mechanism which invalidates URLs using the control port (usually on 6082) with a shared secret to authenticate. 

By default the operator puts `-T 127.0.0.1:6082`, so we found a way round this with `args`, and setting the secret with `admAuth` : 

```yaml
---
apiVersion: caching.ibm.com/v1alpha1
kind: VarnishCluster
metadata:
  labels:
    operator: varnish
  name: varnish-cluster
spec:
   [snip]
    admAuth:
        secretName: varnish-custom-secret
        key: varnish-custom-secret
    args: ["-T", "0.0.0.0:6082"]
```
We also need to add a Service object that points to that so it can be acceded from the pods using `varnish-cli:6082`. 

Could there be a less "manual" way to make it easier for other people ? We'd be happy to give feedback and help test if there is a way to enable this type of feature.
