### ISSUE TITLE
Add affinity in the templates of the deployment  of the operator

### ISSUE THREAD

**Issue by nilbacardit26** [IBM/varnish-operator#51]
Now, it is not possible to assign the controller to an specific node.

I can make the PR myself. Can I have access to the repo?

**Comment by nilbacardit26** [comment]
it would be like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator: varnish-operator
  name: varnish-operator
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      operator: varnish-operator
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        operator: varnish-operator
    spec:
      serviceAccountName: varnish-operator
      containers:
      - name: varnish-operator
        image: {{ .Values.container.image | quote }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy | title | quote }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: LEADERELECTION_ENABLED
          value: {{ if gt .Values.replicas 1.0 }}"true"{{ else }}"false"{{ end }}
        - name: CONTAINER_IMAGE
          value: {{ .Values.container.image | quote }}
        - name: WEBHOOKS_ENABLED
          value: "true"
        - name: LOGLEVEL
          value: {{ .Values.logLevel | quote }}
        - name: LOGFORMAT
          value: {{ .Values.logFormat | quote }}
        resources: {{ toYaml .Values.container.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            port: 8234
            path: /readyz
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
        ports:
          - containerPort: 8329
            name: metrics
          - containerPort: 7340
            name: webhook
          - containerPort: 8234
            name: healthz
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: varnish-operator-webhook-server-cert
            items:
              - key: cert
                path: tls.crt
              - key: key
                path: tls.key
      restartPolicy: {{ .Values.container.restartPolicy | quote }}
      {{- with .Values.container.imagePullSecret }}
      imagePullSecrets:
      - name: {{ . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 10
```
